# This is a basic workflow to help you get started with Actions

name: CI

# push
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.0.5
        with: 
          activate-conda: true
      - run: conda --version
      - run: conda env update --file environment.yml --name base
      - run: which python
      - name: run python program to read from mongo and train a model
        env: # Or as an environment variable
          DB: ${{ secrets.DB }}
          COLLECTION: ${{ secrets.COLLECTION }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python3 run.py
