name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "2.7"]
    steps:
      - uses: conda-incubator/setup-miniconda
        with:
          activate-environment: base
          environment-file: environment.yml
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash
        run: conda info
      - name: Conda list
        shell: bash
        run: conda list
      - name: run python program to read from mongo and train a model
        env: # Or as an environment variable
            DB: ${{ secrets.DB }}
            COLLECTION: ${{ secrets.COLLECTION }}
            HOST: ${{ secrets.HOST }}
            PORT: ${{ secrets.PORT }}
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python3 run.py
