name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda init bash
        $CONDA/bin/conda env update --file environment.yml --name base
        $CONDA/bin/conda activate base
    - name: run python program to read from mongo and train a model
      env: # Or as an environment variable
          DB: ${{ secrets.DB }}
          COLLECTION: ${{ secrets.COLLECTION }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python3 run.py
